Re-adjust the overall styling of top and left nav bar and add image to qrcode and share button
TeyvatLore/TeyvatLore pull request #6
Opened 2022-02-08 16:06 UTC by ALeafWolf

2022-02-09 08:07 UTC, diauweb commented on pages/index.vue
> +  background: url("~@/assets/images/nav_logo_bg.png") no-repeat;
我们现在有两层nav了

2022-02-09 08:07 UTC, diauweb commented on pages/index.vue
> +  font-family: "汉仪文黑";
```suggestion
  font-family: "HYWenHei";
```
这里忘改了（（

2022-02-09 23:59 UTC, ALeafWolf commented
右侧地标资料卡的基本UI搞定了，不过卡的弹出收回按钮有点bug，点了一下后就没法再点了，需要帮忙看一下（挠头

2022-02-10 16:15 UTC, diauweb requested changes

2022-02-10 16:15 UTC, diauweb commented on pages/index.vue
> +            <img id="card-bg" src="~/assets/images/location_details_bg.png">
自己画 不要贴图比较好

2022-02-10 16:15 UTC, diauweb commented on pages/index.vue
> +                <button @click="toggleLocationDetailCard()">
这里缩进去之后按钮就不知道被排版到哪里去了，问题同上 应该自己画这个按钮

2022-02-10 16:15 UTC, diauweb commented on pages/index.vue
> +          <div id="location-detail-card">
拆成组件？

2022-02-10 16:15 UTC, diauweb commented on pages/index.vue
> +          :class="!isDetailCardOpen && 'hide-card'"
```suggestion
          :class="{ 'hide-card': !isDetailCardOpen }"
```

2022-02-10 16:15 UTC, diauweb commented on pages/index.vue
> +              "
可不可以控制一下你的formatter 别折这么离谱的行（

2022-02-10 16:15 UTC, diauweb commented on pages/index.vue
> +        <l-control position="topleft">
why `topleft`

2022-02-10 16:15 UTC, diauweb commented on pages/index.vue
> +    }) {
formatting 问题同上，无关紧要的类型超行就超行吧 这么拆开没法读了 最主要的是尽量别动没有实际修改的部分 咱们目前主要都在这一个文件里堆着干活 会起冲突的（（

2022-02-10 16:15 UTC, diauweb commented on pages/index.vue
> +  height: 100%;
尽量不要混用 `@apply` 和普通样式
另外这里可以直接写进 classname
```suggestion
  @apply absolute flex right-0 mt-1 z-10 h-full;
```

2022-02-10 16:15 UTC, diauweb commented on pages/index.vue
> +  flex-grow: 1;
```suggestion
  @apply glow;
```

2022-02-10 16:15 UTC, diauweb commented on pages/index.vue
> +  border-top-right-radius: 10px;
```suggestion
  @apply rounded-t-xl;
```

2022-02-10 16:15 UTC, diauweb commented
另 解决问题后请点击 Resolve Conversation

2022-02-11 15:20 UTC, ALeafWolf commented on pages/index.vue
> +  height: 100%;
啊那如果说有不得不有自己写的style，比如上个背景图片啥的，我就全写成普通的css还是？

2022-02-11 15:29 UTC, ALeafWolf commented on pages/index.vue
> +  flex-grow: 1;
![image](https://user-images.githubusercontent.com/51769728/153619843-d8b64cf4-6930-4e6a-922f-b75133e0cecd.png)
compiler说没有tailwind里没有grow这个class，虽然官网里确实有(挠头

2022-02-12 02:25 UTC, diauweb commented on pages/index.vue
> +  flex-grow: 1;
那就不用了（

2022-02-12 02:29 UTC, diauweb commented on pages/index.vue
> +  height: 100%;
具体看需要写多少`@apply`多少手工style吧 如果可能的也许可以拆成两部份样式 :thinking:

2022-02-12 04:27 UTC, diauweb approved these changes

2022-02-12 06:39 UTC, LoTwT reviewed
<template>块建议加空行或者注释，更方便阅读 (小声

2022-02-12 07:50 UTC, LoTwT approved these changes

2022-02-12 07:53 UTC, merged